export type TargetIDE = 'Generic' | 'Cursor' | 'Windsurf' | 'Replit' | 'Devin' | 'Lovable' | 'v0' | 'Bolt' | 'Virillama';

export const IDE_OPTIONS: TargetIDE[] = [
    'Generic',
    'Cursor',
    'Windsurf',
    'Replit',
    'Devin',
    'Lovable',
    'v0',
    'Bolt',
    'Virillama'
];

export function enhancePrompt(userPrompt: string, ide: TargetIDE): string {
    let ruleFile = "project guidelines";

    switch (ide) {
        case 'Cursor': ruleFile = ".cursorrules"; break;
        case 'Windsurf': ruleFile = ".windsurfrules"; break;
        case 'Replit': ruleFile = ".replit"; break;
        case 'v0': ruleFile = "components.json"; break; // v0 usually looks for shadcn config
        default: ruleFile = "project configuration files"; break;
    }

    return `ROLE: Expert AI Architect specialized in Context Engineering.
GOAL: ${userPrompt}

PHASE 1: CONTEXT SELECTION (Selecting)
- Before writing code, use \`file_search\` to locate ${ruleFile}, \`CONTRIBUTING.md\`, or \`README.md\`.
- READ these files to load stylistic constraints into your context window.

PHASE 2: SCRATCHPAD (Writing)
- DO NOT start coding yet.
- Use \`file_create\` to generate a \`_plan.md\` (or \`scratchpad.md\`) file.
- Write a step-by-step implementation plan in this file. This serves as your external memory.

PHASE 3: ISOLATED EXECUTION (Isolating)
- Execute the plan step-by-step using the appropriate tools (\`file_edit\`, \`terminal_run\`).
- Focus on one file at a time to keep context clean.
- Refer back to \`_plan.md\` to track progress.

PHASE 4: COMPRESSION & CLEANUP (Compressing)
- Once finished, delete the \`_plan.md\` file (or move to \`docs/\`).
- Update the \`CHANGELOG.md\` with a summary of changes.`;
}

export function generateRuleFileContent(ide: TargetIDE, contextSummary: string): { filename: string, content: string } {
    const timestamp = new Date().toISOString();
    const baseContent = `# Project Context & Rules
# Generated by ContextCode on ${timestamp}

## Project Summary
${contextSummary || "No specific context provided."}

## Behavioral Rules
`;

    let specificContent = "";
    let filename = "rules.txt";

    switch (ide) {
        case 'Cursor':
            filename = ".cursorrules";
            specificContent = `
- Always use the provided tools to explore the codebase.
- When editing, verify file paths explicitly.
- Focus on clean, maintainable code.
- If unsure, ask clarifying questions.
`;
            break;
        case 'Windsurf':
            filename = ".windsurfrules";
            specificContent = `
- Maintain deep context awareness.
- Analyze data flow before making changes.
- Respect the existing project architecture.
`;
            break;
        default:
            filename = `${ide.toLowerCase()}_rules.md`;
            specificContent = `
- Act as an expert developer for ${ide}.
- Follow best practices for this environment.
`;
            break;
    }

    return {
        filename,
        content: baseContent + specificContent
    };
}
